### ISSUE TITLE
failed instance not deleted during the following succesful deployment.

### ISSUE THREAD

**Issue by yannicl** [emerald-squad/cf-zero-downtime-resource#7] opened 2018-09-25 20:41 UTC
**Describe the bug**
When a deployment failed, a failed instance is created. This instance should be deleted during the next deployment. Otherwise the failed instance and the normal (new) one are running concurrently.

**To Reproduce**

1. Revert successful

CF: Application "depot-elements-statiques-dev stopped.
CF: Deleted depot-elements-statiques-dev-failed
CF: Renamed depot-elements-statiques-dev to depot-elements-statiques-dev-failed
CF: Renamed depot-elements-statiques-dev-venerable to depot-elements-statiques-dev
Revert successful!

2. Succesful deployment

CF: Deleted depot-elements-statiques-dev-venerable
CF: Renamed depot-elements-statiques-dev to depot-elements-statiques-dev-venerable

**Comment by ukabu** [comment] 2018-09-27 02:15
From the logs you provided, it seems that the failed instance will not be in running state after a failed deployed.
Also, if the previously failed instance can't be deleted, it's probably because of a service binding that cannot be removed. There isn't much we can do about that besides keeping multiple `-failed` apps around (ex: `-failed.1`, `failed.2`). We are keeping the `-failed` to make debugging easier (to keep access to the recent logs).
If you can reproduce tte scenario with the revert where a `-failed` app cannot be deleted, please `provide the logs of `cf apps | grep "depot-elements-statiques-dev"` to demonstrate which applications are in running state after the failed deploy.

**Comment by ukabu** [comment] 2018-09-27 20:55
I'm closing this issue. If you do get more information/logs, feel free to reopen it.

**Closed by ukabu** 2018-09-27 20:55 UTC
